name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push:
    branches:
      - "master"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: mhughdo
          template: classic
          base: header, activity, community, metadata
          config_timezone: Asia/Saigon

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_languages: yes

          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15

          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://hughdo.dev
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
